# cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg', 'DOCKER_BUILDKIT=1',
      '--cache-from', '${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REGISTRY_REPOSITORY}/${_SERVICE_NAME}:${_SHORT_SHA}',
      '--tag', '${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REGISTRY_REPOSITORY}/${_SERVICE_NAME}:${_SHORT_SHA}',
      '.'
    ]
    env:
      - 'DOCKER_BUILDKIT=1' # Still needed for BuildKit to be enabled for this step
  
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      '${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REGISTRY_REPOSITORY}/${_SERVICE_NAME}:${_SHORT_SHA}']

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "2400s"



